### ISSUE TITLE
Volumes not mounting correctly

### ISSUE THREAD

**Issue by AngieB** [dell-cloud-marketplace/docker-redmine#2]
Hi, for some reason the volumes are not being mounted correctly within the guest. 

On guest it shows /app/redmine but the directory is empty, so none of the plugins that I've added have been migrated.   

Any idea why this would be happening?

**Comment by sakrai** [comment]
Hi Angie,

When you first run the docker container with the volume mapping -v /app/redmine:/app/redmine does the folder /app/redmine contain any contents?
